---
title: "Class 14"
output: github_document
---

## Asthma SNPs in MXL Population 

```{r}
#read file from Ensemble
mxl <- read.csv("373531-SampleGenotypes-Homo_sapiens_Variation_Sample_rs8067378.csv")
head(mxl)
```

```{r}
mxl$Genotype..forward.strand.
```

How many G|G genotypes?
```{r}
table(mxl$Genotype..forward.strand.)
```
or 
```{r}
GG <- sum(mxl$Genotype..forward.strand. == "G|G")
GG
```

```{r}
# %GG
total.genotypes <- sum(table(mxl$Genotype..forward.strand.))
GG/total.genotypes *100
```


# RNA-Seq

Fastq quality scores

Does the first sequence have good quality?
```{r}
#install.packages("seqinr")
library(seqinr)

#install.packages("gtools")
library(gtools)

#interpret
q <- "D D D D C D E D C D D D D B B D D D C C @ "
asc(s2c(q)) -33
```

# Population scale analysis

Does the genotype for rs8067378 influence expression of the important asthma linked genes we found?

```{r}
geno <- read.table("rs8067378_ENSG00000172057.6.txt")
head(geno)
```

```{r}
table(geno$geno)
```

```{r}
inds.gg <- geno$geno == "G/G"
summary( geno$exp[inds.gg])
```

```{r}
inds.aa <- geno$geno == "A/A"
summary( geno$exp[inds.aa])
```

```{r}
inds.ag <- geno$geno == "A/G"
summary( geno$exp[inds.ag])
```

Figure showing distribution of these expression values 

```{r}
boxplot(exp ~ geno, geno)
```






