---
title: "Class 6 Homework"
author: "Nasha Luevit"
date: "1/24/2019"
output: html_document
---

```{r}
#install.packages("bio3d")
```
# Can you improve this analysis code?
```{r}
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug

s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")

s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b

plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```


### Q6:  How would you generalize the original code above to work with any set of input protein structures?

new code
```{r}
library(bio3d)
bfplot <- function(x, chain = "A", atom_type = "CA") {
  #read pdb database 
  sx <- read.pdb(x)
  #trim file to desired chain identifier and atom type
  sx.chainY <- trim.pdb(sx, chain = chain, elety = atom_type)
  #beta factor for protein
  sx.b <- sx.chainY$atom$b
  #beta factor line plot
  plotb3(sx.b, sse = sx.chainY, type = "l", ylab = "Bfactor")
}
#function takes input protein and plots effect of drug binding 
```

test code
```{r}
bfplot("4AKE", "A", "CA")
bfplot("1AKE")
bfplot("1E4Y")
```

